/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a Compass_adapter Compass.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COMPASS_ADAPTER_H
#define COMPASS_ADAPTER_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface local.Compass
 */
class CompassAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "local.Compass")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"local.Compass\">\n"
"    <method name=\"get_data\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    CompassAdaptor(QObject *parent);
    virtual ~CompassAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    double get_data();
Q_SIGNALS: // SIGNALS
};

#endif
